---
- hosts: all
  user: vagrant
  sudo: True

  tasks:

  - name: 基本的なパッケージをインストール
    apt: pkg={{ item }} state=latest update_cache=yes
    tags:
    - packages
    with_items:
    - build-essential
    - libsqlite3-dev
    - libreadline6-dev
    - libgdbm-dev
    - zlib1g-dev
    - libbz2-dev
    - sqlite3
    - tk-dev
    - zip
    - git

  - name: apacheのインストール
    apt: pkg=apache2 state=latest update_cache=yes
    tags:
    - apache

  - name: apacheを起動
    service: name=apache2 state=started
    tags:
    - apache

  - name: MySQLのインストール
    apt: pkg=mysql-server-5.5 state=present update_cache=yes
    tags:
    - mysql

  - name: MySQLを起動
    service: name=mysql state=started
    tags:
    - mysql
